version: '3.3'

services:
  uam:
    image: debian:bullseye-slim
    container_name: uam
    hostname: uam
    restart: unless-stopped
    stop_grace_period: 5s
    ulimits:
      rtprio: 95
      memlock: -1
    volumes:
      - "./entrypoint.sh:/opt/entrypoint.sh"
      - "/opt/uam_data:/root/.uam"
    command: /bin/sh -c "chmod +x /opt/entrypoint.sh && /opt/entrypoint.sh $${PBKEY}"
    ports:
      - "127.0.0.1:17099:17099"
      - "4156:4156"
    environment:
      - PBKEY=
