name: run-docker-compose-workflow
on: #change to push when it's all working
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: cd uam && PBKEY=${{ secrets.PBKEY }} docker-compose up -d
      - name: Sleep until uam is running
        run: sleep 100s
        shell: bash
      - name: Test if port is open
        run: nc -z -w30 127.0.0.1 4156
